version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/frontend/app
    networks:
      - microservices-network

  auth:
    build:
      context: ./auth-microservice
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - auth-microservice/.env
    volumes:
      - .:/auth-microservice/app
    networks:
      - microservices-network
  
  patient:
    build:
      context: ./patient-microservice
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - patient-microservice/.env
    volumes:
      - .:/patient-microservice/app
    networks:
      - microservices-network
  
  doctor:
    build:
      context: ./doctor-microservice
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - doctor-microservice/.env
    volumes:
      - .:/doctor-microservice/app
    networks:
      - microservices-network
  
  appointment:
    build:
      context: ./appointment-microservice
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    env_file:
      - appointment-microservice/.env
    volumes:
      - .:/appointment-microservice/app
    networks:
      - microservices-network
      
networks:
  microservices-network:
    driver: bridge
