services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
