<v-text-field
          v-model="time"
          :active="menu2"
          :focus="menu2"
          label="Picker in menu"
          prepend-icon="mdi-clock-time-four-outline"
          readonly
        >
          <v-menu
            v-model="menu2"
            :close-on-content-click="false"
            activator="parent"
            transition="scale-transition"
          >
            <v-time-picker
              v-if="menu2"
              v-model="time"
              full-width
            ></v-time-picker>
          </v-menu>
        </v-text-field>version: "3.8"

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true