version: "3.8"

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "5000:5000"
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
