version: "3.8"

services:
  appointment:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "5003:5003"
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true