version: "3.8"

services:
  patient:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
