version: "3.8"

services:
  patient:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "5001:5001"
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
