version: "3.8"

services:
  patient-microservice:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
