version: "3.8"

services:
  doctor:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "5002:5002"
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true